### ISSUE TITLE
Join into exisiting project

### ISSUE THREAD

**Issue by cherrythia** [nus-kbb/kbb-frontend#22]
@sweiyang , small bug. New user join into existing project with tasks. 

After joining existing project with tasks. The existing tasks are not showing because we need to refresh_cards again, and get all users (for my assigned users drop down later) 

![image](https://user-images.githubusercontent.com/10574652/236654644-aa9ec8b3-fb1f-484e-9b01-72d12901fd3a.png)

Similar for create project, need to get all users for project id so that when i update task i know

**Comment by cherrythia** [comment]
![image](https://user-images.githubusercontent.com/10574652/236668038-bbce81d1-d1cb-47dd-9802-17523d301187.png)
somehow after joining the projectid is still null. Not sure why never set sessionToken in

**Comment by sweiyang** [comment]
@cherrythia fixed
